---
# Apache handlers

- name: Restart apache
  service:
    name: "{{ apache_service }}"
    state: restarted

- name: Reload apache
  service:
    name: "{{ apache_service }}"
    state: reloaded

- name: Stop apache
  service:
    name: "{{ apache_service }}"
    state: stopped

- name: Start apache
  service:
    name: "{{ apache_service }}"
    state: started
