name: Bug Report
description: Report a bug or issue with Ahab
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what you were trying to do and what went wrong.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: Tell us what you expected!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide the exact steps to reproduce the issue.
      placeholder: |
        1. Run `make install`
        2. Execute `make install apache`
        3. See error...
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Fedora)
        - Linux (Debian)
        - Windows with WSL2
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: virtualization-provider
    attributes:
      label: Virtualization Provider
      description: Which virtualization provider are you using?
      options:
        - VirtualBox
        - VMware Fusion (macOS)
        - VMware Workstation (Windows/Linux)
        - KVM/libvirt
        - Other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: command-output
    attributes:
      label: Command output
      description: Please paste the full output of the failing command.
      render: shell
      placeholder: |
        $ make install apache
        [paste full output here]

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        - System specifications (RAM, CPU)
        - Any modifications you made to the default setup
        - Other software that might be interfering