---
# PHP handlers

- name: Restart apache
  service:
    name: "{{ apache_service }}"
    state: restarted

- name: Reload apache
  service:
    name: "{{ apache_service }}"
    state: reloaded

- name: Restart php-fpm
  service:
    name: php-fpm
    state: restarted
  when: php_fpm_enabled | default(false)

- name: Reload php-fpm
  service:
    name: php-fpm
    state: reloaded
  when: php_fpm_enabled | default(false)
